name: The Agency
favicon: null
layout_spectrum: 0.46725
typography_spectrum: 0.49971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28263e'
    - '#dec7a5'
    - '#c48c69'
    - '#627fc1'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
